export const REQUEST_SEND_MESSAGE = 'MESSAGE/SEND';
export type REQUEST_SEND_MESSAGE = typeof REQUEST_SEND_MESSAGE;

export const ERROR_SEND_MESSAGE = 'MESSAGE/ERROR';
export type ERROR_SEND_MESSAGE = typeof ERROR_SEND_MESSAGE;

export const SUCCESS_SEND_MESSAGE = 'MESSAGE/SUCCESS';
export type SUCCESS_SEND_MESSAGE = typeof SUCCESS_SEND_MESSAGE;
